Made ReadMe file for KUOSC.
kuosc2005/website pull request #11
Opened 2023-08-14 02:23 UTC by felixop7

Made a readme file for KUOSC.
#7 solved.

2023-08-14 17:13 UTC, aadarshadhakalg commented on README.md
> +The Kathmandu University Open Source Project (KUOSC) website aims to provide an open and collaborative platform for showcasing the innovative projects, research, and contributions made by the Kathman
** contributions made by community members **

2023-08-14 17:17 UTC, aadarshadhakalg commented on README.md
> +#Getting-Started
may be we can rename this to 'Before you build this site'?

2023-08-14 17:19 UTC, aadarshadhakalg commented on README.md
> +Thank you for your interest in the Kathmandu University Open Source Project (KUOSC) website. We hope this README provides a clear understanding of our project's purpose, features, installation, and c
We don't need this.

2023-08-14 17:24 UTC, aadarshadhakalg requested changes
Thank you for the PR @felixop7.  Please address the changes that have been requested.

2023-08-14 17:25 UTC, aadarshadhakalg commented on README.md
> +Research Highlights: Discover groundbreaking research initiatives undertaken by the university's scholars.
Just the line no 22

2023-08-15 02:47 UTC, felixop7 commented
Done @aadarshadhakalg

2024-02-21 13:55 UTC, aadarshadhakalg commented
@felixop7  Still some issues need to be addressed. If you can manage some more time to work on this that would be appreciated.

2024-05-18 09:49 UTC, closed without merging